spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true
      path: /data
      settings:
        web-allow-others: true
        
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:http://localhost:9092}
    consumer:
      bootstrap-servers: ${KAFKA_CONSUMER_BOOTSTRAP_SERVER:localhost:9092}
    producer:
      bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVER:localhost:9092}
    properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000

  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_URL:http://localhost:9090}

  sleuth:
    integration:
      enabled: true
    sampler:
      probability: 1
      
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

  eureka:
    client:
      service-url:
        default-zone: ${EUREKA_URL}
    instance:
      instance-id: ${spring.application.name}:${random.uuid}
      appname: ${spring.application.name}

refresh:
  value: abcdefg

debug: ${DEBUG:false}
