spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:shipmentdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:9090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    appname: shipment-service