spring:
  datasource:
    url: jdbc:h2:mem:shipmentdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      group-id: ecom-shipment-service
      auto-offset-reset: earliest